
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tptsiafkdkzhntyidvpv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRwdHNpYWZrZGt6aG50eWlkdnB2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU5NDQ5NDQsImV4cCI6MjA2MTUyMDk0NH0.k3M7hdawHfe1hkkP-olvo16HlfcUyDa9d_0ZrH2A-PE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    flowType: 'pkce',
    autoRefreshToken: true,
    persistSession: true,
    detectSessionInUrl: true,
  }
});
